### ISSUE TITLE
Updating requirements

### ISSUE THREAD

**Issue by jansowinski** [Calamari/facebook-cleaner#4]
Hi, great project! 

I think it'll be worth adding two requirements to README: 

- [chromedriver](http://chromedriver.storage.googleapis.com/index.html) - after just cloning repo, typing `bundle` and `ruby run.rb` I got errors about not having chromedriver in PATH, I think I'ts worth adding info about that to tutorial - it'll save some time to newcomers.
- If you have selected language other than English (UK) in facebook settings, this script won't work (see  #5 and PR connected with that), so I think it's woth adding line about it to requirements

[edited] - it's more informative now :)

**Comment by Calamari** [comment]
Both are good ideas, will do those in the evening :)

**Comment by Calamari** [comment]
So, I just added some lines about selenium and the language. You think it is good enough [tm] now?

**Comment by jansowinski** [comment]
It's great now! :)
