### ISSUE TITLE
Is it planned to make a Ruby Gem out of it?

### ISSUE THREAD

**Issue by casi** [Calamari/facebook-cleaner#7]
..I would be glad. Regardless, thanks for this cool script! :)

**Comment by Calamari** [comment]
Hey.

You're welcome :)

I have no plans to make it a gem yet. And I wonder what the usecase of it being a rubygem could be?

**Comment by casi** [comment]
Thanks for reply.

Well, i think it's easier to install somewhere in a project and you only need to ```gem update``` if you need an update. Anyway, just asking.

**Comment by Calamari** [comment]
Hmm, I don't see the reason for having it in a project somewhere, because it is a command line script, but I totally get the `gem update` argument :) If I will have some time, I might add it.

**Comment by casi** [comment]
ok, thanks!
