### ISSUE TITLE
#<NoMethodError: undefined method `location_once_scrolled_into_view' for nil:NilClass>

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [Calamari/facebook-cleaner#8]
Hi,

when I run your script I get following error message after logging in successfully:

#<NoMethodError: undefined method `location_once_scrolled_into_view' for nil:NilClass>

> ruby 2.3.4p301 (2017-03-30 revision 58214) [x86_64-darwin16]

**Comment by h0jeZvgoxFepBQ2C** [comment]
Looks like I had to switch to english to make it work!

**Comment by Calamari** [comment]
Yeah, that script uses the text on the buttons figure out, which button to click.
I think I wrote also a note in the readme about that. :)
